### ISSUE TITLE
cannot "carthage update" in Xcode Version 7.1 (7B91b)

### ISSUE THREAD

**Issue by arbipher** [behrang/YamlSwift#15]
```
$> carthage update
  1 github "behrang/YamlSwift.git"
*** Cloning YamlSwift
*** Checking out YamlSwift at "1.2.2"
*** xcodebuild output can be found in /var/folders/zz/_f397zk95zl90q80sm1qr1d40000gn/T/carthage-xcodebuild.ApCYFW.log
*** Building scheme "Yaml OSX" in Yaml.xcodeproj
  1 github "SwiftyJSON/SwiftyJSON"

** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/ex/Desktop/workspace/summer/Telling/Carthage/Checkouts/YamlSwift/YamlTests/ExampleTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/ex/Desktop/workspace/summer/Telling/Carthage/Checkouts/YamlSwift/YamlTests/ExampleTests.swift:454:17: error: reference to property 'exampleYaml' in closure requires explicit 'self.' to make capture semantics explicit
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/ex/Desktop/workspace/summer/Telling/Carthage/Checkouts/YamlSwift/YamlTests/ExampleTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

**Comment by DarkRockman** [comment]
I'm having this issue as well, following is a paste from offending terminal output

*** Building scheme "Yaml iOS" in Yaml.xcodeproj
*** Building scheme "Yaml OSX" in Yaml.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/monsanto/Downloads/SwiftLint-master/Carthage/Checkouts/YamlSwift/YamlTests/ExampleTests.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)

**Comment by DarkRockman** [comment]
@arbipher  The solution for this is already in source code as merge has occured, but this has not been tagged. In the meantime you can compile your own YAML framework by compiling the source code until the tag is created

**Comment by behrang** [comment]
Sorry for the delay. Tagged latest release and it should now be fixed.
