### ISSUE TITLE
switch Foundation dependant code to Standard Library

### ISSUE THREAD

**Issue by revanistT3** [behrang/YamlSwift#19]
swift 2 is getting more popular, especially as it has become open source. The type of people who go to github are likely using open source tools (swift 2) and operating systems. Linux (an open source os) only supports swift 2.

**Comment by behrang** [comment]
I don't get the question or issue. Swift 2.2 is supported and if there is any problem with Linux, please be more specific.

**Comment by revanistT3** [comment]
[output.txt](https://github.com/behrang/YamlSwift/files/122410/output.txt)

swift 2.2, ubuntu 15.10, x86_64. Not sure if it's a linux problem, seems to involve Foundation. I'm not familiar it, I'm not sure if it's even implemented in linux completely yet, I believe it's in an overhaul to clean/include more platforms.

**Comment by behrang** [comment]
You're right. It seems to be because of Foundation support on Linux. I keep this open, until there is a solution for this.

**Comment by revanistT3** [comment]
excuse my ignorance, but what is the benefit of using things like Foundation and NSString vs the swift standard library?

**Comment by behrang** [comment]
At the time I started, I needed classes in Foundation. It might not be required anymore as Swift's library is improving. I keep this open and when I had time, I'll look at it.

You may also check it and try to change problematic parts and send me a pull request.

**Comment by revanistT3** [comment]
thanks, I'll look at it

**Comment by revanistT3** [comment]
sorry again, new to swift and especially github. I have cloned the repo with ssh and tried to push changes with cli but got a permission error. How do I propose changes and can I associate it with this issue?

also know anyway to convert NSRegularExpression to a String?

**Comment by behrang** [comment]
You have to fork this repo, make changes, and after that use github to send a pull request.

I'm not sure what you mean by converting NSRegularExpression to a String.

**Comment by revanistT3** [comment]
#21 clears a good amount of errors on my end without adding new ones, it also makes the code more readable and "swifty"

**Comment by revanistT3** [comment]
I just realised it would probably be smart to break this issue into multiple ones. Looking back on it, I can easily break it down into 3.

**Comment by behrang** [comment]
You may do it. The important thing is that new changes don't break anything. Also try to run tests before pushing.

**Comment by revanistT3** [comment]
I'll try to keep testing in mind. Unfortunately the project never built for me, so I can only test fragments and push without creating NEW compiler errors

**Comment by revanistT3** [comment]
fixed those errors, the commands were being evaluated out of order

**Comment by jpsim** [comment]
Given that this project has supported Linux since #30 was merged, I think this can be closed now.

**Comment by behrang** [comment]
Thanks for helping me in this.
