### ISSUE TITLE
CocoaPods spec for 1.4.2 not on trunk yet

### ISSUE THREAD

**Issue by janukobytsch** [behrang/YamlSwift#23]
The Podspec for 1.4.2 has not been pushed to the CocoaPods spec repo yet (latest there is 1.4.1). Since I am using this library in a custom framework that I want to link against tvOS, I'm depending on the tvOS platform support in the Podspec file in 1.4.2 (which forces me to roll my own spec repo atm). Would really appreciate seeing the latest version on CocoaPods!

**Comment by behrang** [comment]
Pushed 1.4.3.
