### ISSUE TITLE
Indirect enum

### ISSUE THREAD

**Issue by seivan** [behrang/YamlSwift#24]
Although I don't fully understand the indirect concept for enums, I am wondering if it might be applicable here https://github.com/behrang/YamlSwift/blob/master/Yaml/Yaml.swift ? 

Check under Recursive Enumerations

https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html

**Comment by behrang** [comment]
I don't have any idea for how that could be useful. Currently in the cases for Array and Dictionary, a Yaml enum is required, but in these cases, an array (`[]`) or a dictionary (`[:]`) plays the role of indirection.

Do you have any idea how that could be useful here?
