### ISSUE TITLE
Prefix Classes and make methods internal. 

### ISSUE THREAD

**Issue by seivan** [behrang/YamlSwift#34]
I know you're not supposed to prefix classes in Swift, now that we got "namespace" support. But I see this as a kind of library that would be used with other libraries more than actual applications. And even in a situation where it's used with applications this wouldn't exactly harm them.

I was hoping to start a discussion about it making everything internal, and also prefixing common names such as `Result`, `Parser` amongst others. It's a nog a big deal but I was hoping to get your take on this.

**Comment by behrang** [comment]
Can you elaborate more and provide some links? I don't have enough experience in this. Currently it is clean and easy. I'm afraid that adding prefixes would make it unfriendly. Is there another way to have another build for those use cases? Are you talking about Objective-C integration only?

**Comment by seivan** [comment]
@behrang Here https://github.com/behrang/YamlSwift/pull/38

This makes your internal and public interface much smaller. 
It also changes to use idiomatic swift with throwing instead of using a Result<T> monad.

I also prefer monads (like optional) but this is actually more common. Nothing stops the next person to wrap the function in their own monad and catch the exception or value. 
In fact, I do that with my Either<L, R> in our project. 

We also host Yaml internally in Xcode instead of using a dynamic framework. This causes clashes with filenames, so I was hoping we could prefix the filenames to.
