### ISSUE TITLE
Update Cocoapods trunk

### ISSUE THREAD

**Issue by khanlou** [behrang/YamlSwift#44]
Do you think you could update the CocoaPods Specs repo? I see your podspec supports version 3.0, but the specs repo only shows up to 1.4.3: https://github.com/CocoaPods/Specs/tree/master/Specs/Yaml

**Comment by khanlou** [comment]
Side note: we need this for https://github.com/jpsim/SourceKitten/pull/292 so that SourceKitten can work with CocoaPods

**Comment by jpsim** [comment]
It would be especially nice if `2.0.1` was also pushed to CocoaPods.

**Comment by behrang** [comment]
Ok, pushed `3.1.0` and `2.0.2`.
