### ISSUE TITLE
Fails to parse (awkward looking?) array

### ISSUE THREAD

**Issue by darrenclark** [behrang/YamlSwift#47]
It appears `YamlSwift` fails to parse this:

```yaml
array: [item1,
item2, item3]
```

The indenting looks a little odd to me.., but it appears to pass the Yaml linters I tried:

- http://yaml-online-parser.appspot.com/?yaml=array%3A+%5Bitem1%2C%0Aitem2%2C+item3%5D&type=json
- http://www.yamllint.com (couldn't find a direct link with the Yaml pre-filled out)

So far I've traced this to be an extra `dedent` token between the two lines, i.e.:

```
... string(item1), comma, dedent, newline, string(item2), ...
```

Any ideas?

---

### Sample code

```swift
import Yaml

let yamlString = "array: [item1,\nitem2, item3]"
Yaml.debug(yamlString)
```

### Output

(line breaks added for readability)

```
====== Tokens:
[(Yaml.Yaml.TokenType.string, "array"),
(Yaml.Yaml.TokenType.colon, ":"), 
(Yaml.Yaml.TokenType.indent, ""), 
(Yaml.Yaml.TokenType.space, " "), 
(Yaml.Yaml.TokenType.openSB, "["),
(Yaml.Yaml.TokenType.string, "item1"), 
(Yaml.Yaml.TokenType.comma, ","), 
(Yaml.Yaml.TokenType.dedent, ""), 
(Yaml.Yaml.TokenType.newLine, "\n"), 
(Yaml.Yaml.TokenType.string, "item2"), 
(Yaml.Yaml.TokenType.comma, ","),
(Yaml.Yaml.TokenType.space, " "), 
(Yaml.Yaml.TokenType.string, "item3"),
(Yaml.Yaml.TokenType.closeSB, "]"),
(Yaml.Yaml.TokenType.end, "")]
~~~~~~
expected comma, near "\nitem2, item3]"
```

**Comment by darrenclark** [comment]
It appears a 3rd linter (http://codebeautify.org/yaml-validator) actually says it is invalid yaml.  Let me dig a little deeper into this.

**Comment by darrenclark** [comment]
If I'm interpreting the spec right, it seems as though it should be valid:

http://yaml.org/spec/1.2/spec.html#id2790726 (see the sample Yaml in Section 7.14)

I think I can fix this. Hopefully a PR is incoming soon...

**Comment by darrenclark** [comment]
Actually, testing it as per the reference parser from http://yaml.org/ (http://ben-kiki.org/ypaste/), it looks like `YamlSwift` is behaving correctly, my apologies!

**Comment by behrang** [comment]
No problem. But if you indent the second line, it will be a valid Yaml document.
