### ISSUE TITLE
Support Swift Package Manager

### ISSUE THREAD

**Issue by lf-araujo** [behrang/YamlSwift#61]
The file structure does not comply with the standard swift package manager.

**Comment by behrang** [comment]
I don't have time to maintain this project. Any help is appreciated.

**Comment by lf-araujo** [comment]
Thank you for answering, I updated the project already. Will you be able to
accept the pushes?

Best,
lf

2017-10-29 21:56 GMT+11:00 Behrang Noruzi Niya <notifications@github.com>:

**Comment by behrang** [comment]
Please send the pull request.

@seivan can you check the pull request?

**Comment by lf-araujo** [comment]
I am new to git and I am facing a problem. I have created a local branch, added the files, commited, however when I try to create a remote branch in order to push (with the command):

```
git push --set-upstream origin SPMsupport

```

I get: 

```
remote: Permission to behrang/YamlSwift.git denied to lf-araujo.
fatal: unable to access 'https://github.com/behrang/YamlSwift/': The requested URL returned error: 403
```

What am I doing wrong?

**Comment by seivan** [comment]
@lf-araujo you're trying to push to `behrang/YamlSwift` when you should be pushing to your own fork.

**Comment by seivan** [comment]
Added in https://github.com/behrang/YamlSwift/pull/62
