### ISSUE TITLE
Are multiline values supported?

### ISSUE THREAD

**Issue by SimplyDanny** [behrang/YamlSwift#67]
I wonder whether multiline values like

```
key: |
    value1
    value2
```

are supported by your library. I always get parse errors trying to read such YAML files.

**Comment by seivan** [comment]
I am uncertain, but for now please use `"value1\nvalue2"` I can look into this when I get some time over.

**Comment by behrang** [comment]
The `parsec` branch is spec compliant and should support it.

**Comment by SimplyDanny** [comment]
Thanks! Maybe you should add a note about the master branch not being fully compliant with the specs.
