### ISSUE TITLE
Release Swift 4 compatible version to Cocoapods?

### ISSUE THREAD

**Issue by daniel-beard** [behrang/YamlSwift#68]
Looks like the most recent version available through cocoapods is 3.3.1. Can we get the latest tag pushed to cocoapods as well please?

**Comment by sghiassy** [comment]
In case its of help, the command is

```
git tag 3.4.0
git push --tags
pod repo push Yaml.podspec --swift-version='4' --allow-warnings --sources='https://github.com/CocoaPods/Specs'
```

**Comment by seivan** [comment]
I'll make sure to get to this since there isn't an automated way of pushing binaries yet, but in the future, I generally suggest using Carthage.

**Comment by daniel-beard** [comment]
@seivan please don't force people to choose, Carthage has it's own set of problems (so does Cocoapods though). Allowing devs to choose which set of trade-offs work for them is a great thing :)

**Comment by seivan** [comment]
@daniel-beard I am not forcing anyone. You're more than welcome to write podspec files, or host your own pointing to the repo. Afaik I know, Cocoapods is still decentralised. But my focus is initially on distributing Carthage binaries frameworks and eventually looking into Swift PM.

**Comment by seivan** [comment]
Should be done, let me know if something's wrong.

**Comment by daniel-beard** [comment]
@seivan thanks for publishing, I tested it out, and looks like a little more is needed. Submitted patch here: https://github.com/behrang/YamlSwift/pull/71
