### ISSUE TITLE
cannot parse this file，but other parser can.

### ISSUE THREAD

**Issue by iCodist** [behrang/YamlSwift#75]
I like YamlSwift, it's so cool, thank you! 

When I parse the following file, it crashed.

[double_pinyin_flypy.schema.yaml.zip](https://github.com/behrang/YamlSwift/files/1815952/double_pinyin_flypy.schema.yaml.zip)

**Comment by seivan** [comment]
Can you paste your YAML [here](https://gist.github.com)

**Comment by iCodist** [comment]
ok

https://gist.github.com/iCodist/df1e74ef7506ce3f19315ba4b7ed10c6

**Comment by seivan** [comment]
@iCodist Can you take a look at https://github.com/behrang/YamlSwift/tree/feature/investigate_char_bug

Seems related to one of the characters (\\xFF0C) used sans quotation marks.
I'm working on a parsec replacement, so I might not get time to get around this. 
Adding quotes resolves the issue: `states: [ "。，", "．，" ]`

Is that good enough?

**Comment by seivan** [comment]
@iCodist Let me know if doesn't work.
